### ISSUE TITLE
Catalog Evaluation - in All shops context view (Multistore)

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/statsmodule#24]
## Tasks
- [x] Group languages under shop name
- [x] Link to product

## Problem description

Is this part of Stats module intended to be used in All shops context with Multistore?

Currently it shows rows with information regarding all shops but it's impossible to decipher which number is for which shop.

![image](https://github.com/thirtybees/statsmodule/assets/11251370/5afeecc6-033a-499f-8dcc-9adde3e8c484)

Could we have header on this table (when Multistore = ON) that display the shop name and if possible could we have the number be a link to this product in this shop context (if this is at all possible?) This will speed the information addition greatly!

Also when in All shops context the number of images is the sum of all images of all shops (even if the images are the same). I one switches to certain shop context this number is correct per shop.

**Comment by getdatakick** [comment]
Indeed, I've never noticed this mess in multistore context.
