### ISSUE TITLE
Enhancement - Shop association tab (if multistore enabled).

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/statsmodule#25]
Currently there is no place where the merchant can see a summarized view of all products and their shop associations.

Could we reuse the Catalog evaluation view and display information regarding the product associations per shop. This tab should be visible only in multistore = ON context.

![image](https://github.com/thirtybees/statsmodule/assets/11251370/e9223cee-a2eb-48d6-ad4b-23cbb7afd835)

- each circle is a toggle switch - ON, OFF, to change the shop associations.
- product names are links (as in the original tab)
- all shops context shown in the sketch up with all products and all shops for ease of control.
- an alert warning field could be displayed under the **Shop association** section in the Product controller with link to this tab and short info for the ability of summarized view and control.
- I know that with those controls we're getting a bit off the 'stats' paradigm but I believe this will be a strong functionality addition.

**Comment by getdatakick** [comment]
Maybe create dedicated stats tab for this? Catalog evaluation is cluttered as already

**Comment by therampagerado** [comment]
Yes, exactly. Just wanted the make the sketch up using the Catalog Evaluation table but it should be in different tab called Catalog association (or something like that). Do you think something like that could be useful for other merchants?

**Comment by getdatakick** [comment]
Sure, there are definitely some merchants that could use such functionality. If you can, please provide PR, we will gladly merge it.

I personally advice against dissociating product from stores, as it is destructive operation -- all shop-related data are deleted. In my opinion, it's better to mark product as not available in the store instead, but keep it associated.

**Comment by getdatakick** [comment]
Closed by PR #30
