### ISSUE TITLE
Missing addCurrentShopRestriction method in statscheckup, Utils, ProductSalesView, statsordersprofit

### ISSUE THREAD

**Issue by niclix** [thirtybees/statsmodule#27]
Method addCurrentShopRestriction is missing, which is used in several stats module.

**Comment by getdatakick** [comment]
This method is part of thirty bees since version 1.2.0

Please update your store to newer version

**Comment by niclix** [comment]
if this is the case the below line MUST be changed in statsmodule.php
$this->tb_min_version = '1.2.0'
So people know that they have to upgrade the TB before upgrading to the latest stats module
