### ISSUE TITLE
Available quantities - pack should not add pack products to the total.

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/statsmodule#28]
Currently when we have a pack of products its value is added to the total twice - once as singular item and once in a pack.

It would be nice if this tab detects pack products and exclude their value. I'm not sure if it should still show their 'Available quantity for sale'. Probably should display '-' as this quantity is not very informative and should not be included in this list.

**Comment by getdatakick** [comment]
Thank you for the PR, I've merged it. 

I don't think price column should be modified, I think it's ok to roll up the price of packs into average price of catalog
